var annotated_dup =
[
    [ "EnumWrap", null, [
      [ "EnumWrapper", "class_enum_wrap_1_1_enum_wrapper.html", "class_enum_wrap_1_1_enum_wrapper" ]
    ] ],
    [ "Nextsim", null, [
      [ "ArgV", "class_nextsim_1_1_arg_v.html", null ],
      [ "BaseElementData", "class_nextsim_1_1_base_element_data.html", null ],
      [ "Chrono", "class_nextsim_1_1_chrono.html", "class_nextsim_1_1_chrono" ],
      [ "CommandLineParser", "class_nextsim_1_1_command_line_parser.html", "class_nextsim_1_1_command_line_parser" ],
      [ "Configurator", "class_nextsim_1_1_configurator.html", null ],
      [ "Configured", "class_nextsim_1_1_configured.html", "class_nextsim_1_1_configured" ],
      [ "ConfiguredBase", "class_nextsim_1_1_configured_base.html", "class_nextsim_1_1_configured_base" ],
      [ "ConfiguredModule", "class_nextsim_1_1_configured_module.html", null ],
      [ "Counterant", "class_nextsim_1_1_counterant.html", "class_nextsim_1_1_counterant" ],
      [ "DevGrid", "class_nextsim_1_1_dev_grid.html", "class_nextsim_1_1_dev_grid" ],
      [ "DevGridIO", "class_nextsim_1_1_dev_grid_i_o.html", "class_nextsim_1_1_dev_grid_i_o" ],
      [ "DevStep", "class_nextsim_1_1_dev_step.html", "class_nextsim_1_1_dev_step" ],
      [ "DummyExternalData", "class_nextsim_1_1_dummy_external_data.html", null ],
      [ "ElementData", "class_nextsim_1_1_element_data.html", "class_nextsim_1_1_element_data" ],
      [ "ExternalData", "class_nextsim_1_1_external_data.html", "class_nextsim_1_1_external_data" ],
      [ "IDevGridIO", "class_nextsim_1_1_i_dev_grid_i_o.html", "class_nextsim_1_1_i_dev_grid_i_o" ],
      [ "IFreezingPoint", "class_nextsim_1_1_i_freezing_point.html", "class_nextsim_1_1_i_freezing_point" ],
      [ "IModelStep", "class_nextsim_1_1_i_model_step.html", "class_nextsim_1_1_i_model_step" ],
      [ "IPrognosticUpdater", "class_nextsim_1_1_i_prognostic_updater.html", null ],
      [ "IStructure", "class_nextsim_1_1_i_structure.html", "class_nextsim_1_1_i_structure" ],
      [ "Iterator", "class_nextsim_1_1_iterator.html", "class_nextsim_1_1_iterator" ],
      [ "LinearFreezing", "class_nextsim_1_1_linear_freezing.html", "class_nextsim_1_1_linear_freezing" ],
      [ "Logged", "class_nextsim_1_1_logged.html", null ],
      [ "Model", "class_nextsim_1_1_model.html", "class_nextsim_1_1_model" ],
      [ "PrognosticData", "class_nextsim_1_1_prognostic_data.html", "class_nextsim_1_1_prognostic_data" ],
      [ "PrognosticGenerator", "class_nextsim_1_1_prognostic_generator.html", null ],
      [ "ScopedTimer", "class_nextsim_1_1_scoped_timer.html", "class_nextsim_1_1_scoped_timer" ],
      [ "SimpleIterant", "class_nextsim_1_1_simple_iterant.html", "class_nextsim_1_1_simple_iterant" ],
      [ "StructureFactory", "class_nextsim_1_1_structure_factory.html", null ],
      [ "Timer", "class_nextsim_1_1_timer.html", "class_nextsim_1_1_timer" ],
      [ "UnescoFreezing", "class_nextsim_1_1_unesco_freezing.html", null ],
      [ "UnusedData", "class_nextsim_1_1_unused_data.html", null ]
    ] ],
    [ "Config1", "class_config1.html", null ],
    [ "Config2", "class_config2.html", "class_config2" ],
    [ "Config3", "class_config3.html", "class_config3" ],
    [ "Impl1", "class_impl1.html", null ],
    [ "Impl2", "class_impl2.html", null ],
    [ "ITest", "class_i_test.html", null ],
    [ "ModuleLoader", "class_module_loader.html", "class_module_loader" ]
];